#!/bin/bash
# Swiftstack service

. /utils.sh

env
cmd=$1
serviceStatus=""

#if [ -n "$gitTag" ]; then
#    agentSendLogMessage  "Found gitTag parameter gitTag = ${gitTag}"
#else
#     agentSendLogMessage  "Didn't find custom parameter gitTag. Using gitTag=master"
#     gitTag="swiftstack container create"
#fi

sudo yum install -y epel-release

sudo yum install -y python-pip

#sudo pip install pip --upgrade

sudo yum install -y python-swiftclient

wget https://raw.githubusercontent.com/bh-public/cc-ss01/master/SS01.py -O SS01.py

# Run the Service

case $cmd in
        start)
                chmod +x SS01.py
                python SS01.py
                serviceStatus="Started"
                ;;
        stop)   
                serviceStatus="Stopped"
                ;;
        *)
                serviceStatus="Error: Not a valid argument"
                exit 127
                ;;
esac
